// Learn more about F# at http://fsharp.org
// See the 'F# Tutorial' project for more help.

open System

[<EntryPoint>]
let main argv = 
    Problem1.solve()
    Problem2a.solve()
    Problem2b.solve()
    Problem3a.solve()
    Problem3b.solve()
    Problem4.solve()
    Problem5a.solve()
    Problem5b.solve()
    Problem6.solve()
    Problem7a.solve()
    Problem7b.solve()
    Problem8.solve()
    Problem9a.solve()
    Problem9b.solve()
    Problem10.solve()
    Problem11.solve()
    Problem12.solve()
    Problem13.solve()
    Problem14.solve()
    Problem15.solve()
    Problem15_BigInteger.solve()
    Problem16.solve()
    Problem16_Functional.solve()
    Problem17.solve()
    Problem18.solve()
    Problem19a.solve()
    Problem19b.solve()
    Problem19b_Faster.solve()
    Problem19b_LinkedList.solve()
    Problem19b_CircularList.solve()
    Problem20.solve()
    Problem21.solveSilver()
    Problem21.solveGold()
    Problem22a.solve()
    Problem22b.solve()
    Problem23.solveSilver()
    Problem23.solveGold()
    Problem24.solve()
    Problem24_HeldKarp.solve()
    Problem25.solve()
    0 // return an integer exit code
